---
- name: Add group called cloudadmins
  group:
    name: cloudadmins
    state: present

- name: Add user accounts and add to groups
  user:
    name: "{{ item }}"
    groups: "cloudadmins,wheel"
    append: yes
    state: present
  loop:
    - user100
    - user200
    - user300

- name: Generate SSH keys for users
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop:
    - user100
    - user200
    - user300

- name: Ensure the SSH directory has correct permissions
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0700'
  loop:
    - user100
    - user200
    - user300

- name: Ensure the SSH key has correct permissions
  file:
    path: "/home/{{ item }}/.ssh/id_rsa"
    state: file
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
  loop:
    - user100
    - user200
    - user300

- name: Check if SSH key exists for user100
  stat:
    path: "/home/user100/.ssh/id_rsa"
  register: user100_ssh_key

- name: Debug SSH key status
  debug:
    var: user100_ssh_key

- name: Download private key for user100 from vm1
  fetch:
    src: "/home/user100/.ssh/id_rsa"
    dest: "~/user100_id_rsa"
    flat: yes
  when: 
    - inventory_hostname == "vm1-n01649908.canadacentral.cloudapp.azure.com"
    - user100_ssh_key.stat.exists
